const firebaseConfig = {
  NEXT_PUBLIC_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:
    process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:
    process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:
    process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  NEXT_PUBLIC_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  COOKIE_SESSION_NAME: process.env.COOKIE_SESSION_NAME,
  NEXT_PUBLIC_FIREBASE_ADMIN_PROJECT_ID:
    process.env.NEXT_PUBLIC_FIREBASE_ADMIN_PROJECT_ID,
  NEXT_PUBLIC_FIREBASE_ADMIN_CLIENT_EMAIL:
    process.env.NEXT_PUBLIC_FIREBASE_ADMIN_CLIENT_EMAIL,
  NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATE_KEY:
    process.env.NEXT_PUBLIC_FIREBASE_ADMIN_PRIVATE_KEY
}

export default firebaseConfig
